### PR TITLE
Main entities setup

### PR DESCRIPTION
**Pull request by Maxlyu254**
1. Implemented the SaveGame use case
2. Partly Implemented the StartGame use case
3. Added isBroke() method to Player
4. Added isGameOver() method to Campaign
5. Other minor fixes

### CODE REVIEW

**Review by sinemsoylemezoglu — DISMISSED** [review]
Thank you Max. You did a very well detailed job. I did not see any incorrect parts.

**Review by mariamustard21 — APPROVED** [review]
Awesome! Thanks for the examples of good use cases!

**Review by celinayueh — COMMENTED** [review]
Good adherence to clean architecture and SOLID design principles.

**Review by celinayueh — DISMISSED** [review]

**Review by adelinewang3 — APPROVED** [review]
Looks good

**Review by sinemsoylemezoglu — APPROVED** [review]
Updates are correct and appropriate for the Clean Architecture Design Patterns and SOLID principles. Your documentations are well-explained for us to understand your code. Further, your coding style is also good and readable. Good job on the Main entities setup Max.

**Review by celinayueh — APPROVED** [review]
Good implementation of Tiles and good documentation.

**Pull request merged**
