### PR TITLE
README Update

### PR DESCRIPTION
**Pull request by mariamustard21**
This used to be the branch for my use case but had to switch the README branch and this one.

### CODE REVIEW

**Review by celinayueh — APPROVED** [review]
Good job with the Draw Card use case Maria! Everything looks to follow clean architecture properly. I think some instance variables like "positive" or "cash" can be renamed to be more clear but everything looks to be correct!

**Comment by mariamustard21** [comment]
> Good job with the Draw Card use case Maria! Everything looks to follow clean architecture properly. I think some instance variables like "positive" or "cash" can be renamed to be more clear but everything looks to be correct!

Thank you! I will change this :)

**Review by celinayueh — APPROVED** [review]
The rules that were added to the README are good!

**Review by adelinewang3 — APPROVED** [review]
This looks good

**Pull request merged**
