### PR TITLE
Finished most of Advance use case

### PR DESCRIPTION
**Pull request by celinayueh**
Changed use case to follow MVVM model and added some getter/setter methods. Will update presenter after view model is pulled.

### CODE REVIEW

**Comment by zhenzeyang** [comment]
Good job so far, and you can delete the Advance file if you don't need it

**Review by Maxlyu254 — APPROVED** [review]
Clean architecture implemented, good job!
Now consider making these changes: 
https://docs.google.com/drawings/d/1guxgc3iXlnha_ts0hO3Yk_yEdKgGnaPNtL6vQpJy02k/edit?usp=sharing
This is our google diagram including many notes, now look into the use case protocols below the use case structure diagram, that is something your use case needed to satisfy in order to work with the view and other use cases.

**Review by sinemsoylemezoglu — APPROVED** [review]
Celina you did a well done job with the functionality of the code; the updated version is correct and appropriate for our MVVM model design for the project. Advance use case follows the Clean Architecture Design patterns and SOLID principles. The readability of your code is adequate and the documentations are enough for us to understand your code, plus your design of the code is also good.

**Review by adelinewang3 — APPROVED** [review]
Good use of docstrings.

**Pull request merged**
