### PR TITLE
Gotojail3

### PR DESCRIPTION
**Pull request by zhenzeyang**
This is newest version of my code

### CODE REVIEW

**Review by adelinewang3 — APPROVED** [review]
Good, don't forget to create test cases

**Review by sinemsoylemezoglu — APPROVED** [review]
Good work, but also resolve conflicts first!

**Review by celinayueh — APPROVED** [review]
Interactor is a lot more concise and clear. Good work on the presenter.

**Review by mariamustard21 — APPROVED** [review]
Nice job!

**Review by adelinewang3 — APPROVED** [review]

**Pull request merged**
