### PR TITLE
README Updated Version

### PR DESCRIPTION
**Pull request by sinemsoylemezoglu**
The updated version of README. I created this pull request before starting to implement the rest to do some brainstorming on what to include in README other than the UofTorontopoly Game Rules Manual. Will implement the information part on how to open the Game Screen and how to use the command lines to play the game. Just for now, I want to make sure if everyone likes the format or not. Feel free to make reviews and comment on this part, please include your opinions.

### CODE REVIEW

**Review by celinayueh — APPROVED** [review]
I like your description Sinem, it's very fun!

**Review by Maxlyu254 — APPROVED** [review]
Good work on the README, but you still need to change your controller for confirm buy property use case. Same for interactors.

Remember that the decision varies from time to time your controller is called, so it should not be an instance variable, and it should implement the CommandPerformer interface.

Your presenter should also update more than the output panel. confirm buy property should also update the player cards and the board panel.

**Comment by sinemsoylemezoglu** [comment]
> Good work on the README, but you still need to change your controller for confirm buy property use case. Same for interactors.
> 
> Remember that the decision varies from time to time your controller is called, so it should not be an instance variable, and it should implement the CommandPerformer interface.
> 
> Your presenter should also update more than the output panel. confirm buy property should also update the player cards and the board panel.

Yes, I am working on that.

**Review by mariamustard21 — APPROVED** [review]
Thank you Sinem for the readme!! very fun but gets information across easily ... I can help with writing the manual and stuff if you would like before we hand it in :)

**Pull request merged**
