### PR TITLE
Trade Use Case

### PR DESCRIPTION
**Pull request by no7thing**

### CODE REVIEW

**Review by Maxlyu254 — APPROVED** [review]
Good changes on the names and texts, but you still need to work on your controller, mainly the dependency and how you change user input text to lists of properties and cash

**Review by Maxlyu254 — DISMISSED** [review]
I approve your shit anyways

**Review by celinayueh — APPROVED** [review]
I like the themed default campaign. Good job updating the presenter!

**Review by sinemsoylemezoglu — APPROVED** [review]
Great work!

**Review by adelinewang3 — APPROVED** [review]

**Pull request merged**
