### PR TITLE
[Update 2] PayRentUseCase

### PR DESCRIPTION
**Pull request by adelinewang3**
Rewrote code to match the MVVM model and clean architecture. I will look at the use case protocol that Max made and make more changes later.

### CODE REVIEW

**Review by Maxlyu254 — APPROVED** [review]
You did step 1 and step 2 pretty well, clean architecture well implemented! now, please think about the following questions:
1. How should other use cases, to be specific, Celina's advance use case, call your use case? What information does the use case need to pass to you? You may need to talk with Celina about this.
2. Which of the three panels do you need to update and how should you update them? What information do you need to pass from interactor to presenter to let the presenter perform its action? Think through these to design your presenting process.

**Review by celinayueh — APPROVED** [review]
Hi Adeline, good work with the clean architecture implementation! It is clear for me how to implement your use case in the Advance use case :)

**Review by Maxlyu254 — APPROVED** [review]
Good work on implementing the clean architecture. Now only your interactor depends on the entities! 

However, you still need to change your output data: your presenter should not be passed with output data and integers. But instead, your presenter should just take in one output data, and every integer or string you need should be inside the output data (because it's a data structure, it's built to house data) Also, you need to update the view models by using the notifyAllListeners() method of the view model.

**Review by celinayueh — DISMISSED** [review]
The changes look solid and follow clean architecture. The presenter looks goof.

**Review by celinayueh — APPROVED** [review]
Looks good like before Adeline!

**Review by celinayueh — APPROVED** [review]
The getters and setters are helpful. Good job!

**Review by mariamustard21 — DISMISSED** [review]
Good job Adeline!!!!!

**Review by celinayueh — APPROVED** [review]

**Review by mariamustard21 — APPROVED** [review]

**Review by sinemsoylemezoglu — APPROVED** [review]

**Pull request merged**
